### ISSUE TITLE
Project summary report updates

### ISSUE THREAD

**Issue by ewels** [NationalGenomicsInfrastructure/ngi_reports#22]
## Stage 1
* [x] Change `Contract` to `Agreement` in template
* [x] Add `NGI Facility`
  * `Genomics Production Stockholm`
  * `Genomics Applications Stockholm`
* [x] Re-write Library construction
  * Can no longer drop quote in, need to use new code system lookup table
  * Break up into bullet points - skip if blank
    * Input (`DNA`, `RNA`, `Library`)
    * Type (many things - eg. `By user`, `Rubicon Thruplex FD`)
    * Option (`Depletion`, `350bp`)
    * Category (`Low Input`)
  * Talk to Mattias to get this
  * If all bullet points are missing / can't parse field then:
    * Throw a warning on the command line (with the contents of the field)
    * Skip the entire section, including header (use `{% if project.variable %}` in template)
* [x] Add to Sequencing Method
  * Add sequencing chemistry to sequencing method
* [x] Swedac Accreditation section
  * If blank should print an empty string
  * Print `Not Applicable` if in database
    * Ask Mattias to add this to the LIMS
  * Use `[Not] Validated under ISO accreditation 17025:2005` instead of `[Not] Swedac accredited`
    * Parse in reports from whatever is stored in the database
  * Make all values dynamic from statusdb
  * Rename fields according to what we actually do
    * `Library preparation`
    * `Sequencing data`
    * `Data Processing`
    * `Data Analysis`

---------

## Stage 2
* [x] Remove tabular data from the report if more than 5 samples
* [x] Always generate `.csv` files of tabular data
* [x] Have explanation of fields in report
* [x] Sample Table - _One row per sample_
  * NGI ID
  * User ID
  * Total Reads
  * >= Q30
  * Sample Pass / Fail Status (from yield)
* [x] Library Table - _One row per sample prep per sample_
  * NGI ID
  * Library Prep
  * Library QC Status
  * Average fragment size
  * Index
* [x] Run Table - _One row per per flow cell lane_
  * Date
  * Flow Cell ID
  * Lane
  * Cluster Yield (Passed Filters)
  * % PhiX
  * >= Q30
  * Sequencing Method

Only test with projects from 2015 - not `J.Lundeberg_14_01`

--------

## THE FUTURE

* Make plots where there are tables
* Use `CLICK` instead of `Argparse` for report specific command line parameters
  * Have option for whether to display tables in report or not

**Comment by guillermo-carrasco** [comment]
wow, this is a cool issue!

**Comment by ewels** [comment]
It took a three hour long meeting to write :smile:

**Comment by senthil10** [comment]
@guillermo-carrasco: Indeed :joy:  Was created by `Markdown Magician` @ewels

**Comment by ewels** [comment]
![markdown](http://cdn.meme.am/instances/54813148.jpg)

**Comment by senthil10** [comment]
Well this is done :)

**Comment by ewels** [comment]
![so much win](http://forum.projectcarsgame.com/attachment.php?attachmentid=216415&d=1440706564&thumb=1)
